### ISSUE TITLE
Required test variables have empty defaults

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-project-factory#88]
Several of the tests have variables with blank defaults when they are actually required (and tests fail to run if they're not provided). For example: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/test/fixtures/full/variables.tf#L55

In general, blank defaults are an anti-pattern which we should strongly avoid. It's against our standards. Please check through all variables again and confirm that everything with a default value *can* be left at the default.

**Comment by aaron-lane** [comment]
This appears to have been fixed.

**Comment by morgante** [comment]
@aaron-lane I'm still seeing empty defaults here: https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/test/fixtures/shared/variables.tf

**Comment by aaron-lane** [comment]
Some of those
